- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted
